name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release(e.g. 1.0.1)'
        required: true

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create GitHub tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          git tag -a "v${{ github.event.inputs.version }}" -m "Release version ${{ github.event.inputs.version }}"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git "v${{ github.event.inputs.version }}"

      
      - name: Revert Git user
        run: |
          git config --global --unset user.name
          git config --global --unset user.email

  build_and_push:
    needs: create_tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@main

      - name: Log in to Docker Hub
        uses: docker/login-action@main
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/minigooglecloudcollector:v${{ github.event.inputs.version }}
          build-args: |
                      GPG_PASSPHRASE=${{ secrets.GPG_PASSPHRASE }}